In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.expand_frame_repr', False)

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/ieee-fraud-detection/sample_submission.csv
/kaggle/input/competitions/ieee-fraud-detection/test_identity.csv
/kaggle/input/competitions/ieee-fraud-detection/train_identity.csv
/kaggle/input/competitions/ieee-fraud-detection/test_transaction.csv
/kaggle/input/competitions/ieee-fraud-detection/train_transaction.csv

In [2]:
!pip install -q mlflow dagshub

import mlflow
import dagshub

dagshub.init(repo_owner='aochi23', repo_name='ml_assn_02', mlflow=True)
mlflow.set_experiment("LogisticRegression_Training")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.0/50.0 kB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 70.2 MB/s eta 0:00:00:00:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 73.1 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 51.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.1/273.1 kB 13.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.4/208.4 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.0/77.0 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 879.5/879.5 kB 30.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 3.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.18.1 requires dacite<2,>=1.9, but you have dacite 1.6.0 which is incompatible.

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=0d76ccfc-cb19-47f8-9cd9-3138ff0775db&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=83c11c1b6e65e1de418bace9f2ec8ce7dc666328e42c6a7dfcad590e80c94772

Accessing as aochi23

Initialized MLflow to track repo "aochi23/ml_assn_02"

Repository aochi23/ml_assn_02 initialized!

<Experiment: artifact_location='mlflow-artifacts:/dec17c2f1cb345b89825ccb452c6407e', creation_time=1777654265488, experiment_id='0', last_update_time=1777654265488, lifecycle_stage='active', name='LogisticRegression_Training', tags={'mlflow.experimentKind': 'custom_model_development'}, trace_location=None, workspace='default'>

# 1. Data Loading

In [3]:
path = "/kaggle/input/competitions/ieee-fraud-detection/"

train_transaction = pd.read_csv(path + "train_transaction.csv")
train_identity    = pd.read_csv(path + "train_identity.csv")

In [4]:
train = train_transaction.merge(train_identity, on="TransactionID", how="left")

train.head()

   TransactionID  isFraud  TransactionDT  TransactionAmt ProductCD  card1  card2  card3       card4  card5   card6  addr1  addr2  dist1  dist2 P_emaildomain R_emaildomain   C1   C2   C3   C4   C5   C6   C7   C8   C9  C10  C11  C12   C13  C14     D1     D2    D3    D4   D5  D6  D7  D8  D9   D10    D11  D12  D13  D14    D15   M1   M2   M3   M4   M5   M6   M7   M8   M9   V1   V2   V3   V4   V5   V6   V7   V8   V9  V10  V11  V12  V13  V14  V15  V16  V17  V18  V19  V20  V21  V22  V23  V24  V25  V26  V27  V28  V29  V30  V31  V32  V33  V34  V35  V36  V37  V38  V39  V40  V41  V42  V43  V44  V45  V46  V47  V48  V49  V50  V51  V52  V53  V54  V55  V56  V57  V58  V59  V60  V61  V62  V63  V64  V65  V66  V67  V68  V69  V70  V71  V72  V73  V74  V75  V76  V77  V78  V79  V80  V81  V82  V83  V84  V85  V86  V87  V88  V89  V90  V91  V92  V93  V94  V95   V96   V97  V98   V99  V100  V101  V102  V103  V104  V105  V106  V107  V108  V109  V110  V111  V112  V113  V114  V115  V116  V117  V118  V119  V120  V121  V122  V123  V124  V125  V126    V127   V128  V129   V130   V131  V132    V133   V134  V135  V136  V137  V138  V139  V140  V141  V142  V143  V144   V145  V146  V147  V148  V149    V150  V151  V152  V153  V154  V155  V156  V157  V158          V159           V160  V161  V162  V163   V164    V165    V166  V167  V168  V169  V170  V171  V172  V173  V174  V175  V176  V177  V178  V179  V180  V181  V182  V183  V184  V185  V186  V187  V188  V189  V190  V191  V192  V193  V194  V195  V196  V197  V198  V199  V200  V201  V202  V203  V204  V205  V206  V207  V208  V209  V210  V211  V212  V213  V214  V215  V216  V217  V218  V219  V220  V221  V222  V223  V224  V225  V226  V227  V228  V229  V230  V231  V232  V233  V234  V235  V236  V237  V238  V239  V240  V241  V242  V243  V244  V245  V246  V247  V248  V249  V250  V251  V252  V253  V254  V255  V256  V257  V258  V259  V260  V261  V262  V263  V264  V265  V266  V267  V268  V269  V270  V271  V272  V273  V274  V275  V276  V277  V278  V279  V280  V281  V282  V283  V284  V285  V286  V287  V288  V289  V290  V291  V292  V293  V294  V295  V296  V297  V298  V299  V300  V301  V302  V303  V304  V305  V306    V307   V308  V309   V310  V311   V312  V313  V314  V315  V316    V317   V318  V319  V320  V321  V322  V323  V324  V325  V326  V327  V328  V329  V330  V331  V332  V333  V334  V335  V336  V337  V338  V339  id_01    id_02  id_03  id_04  id_05  id_06  id_07  id_08  id_09  id_10  id_11     id_12  id_13  id_14 id_15     id_16  id_17  id_18  id_19  id_20  id_21  id_22 id_23  id_24  id_25  id_26 id_27 id_28     id_29        id_30                id_31  id_32      id_33           id_34 id_35 id_36 id_37 id_38 DeviceType                     DeviceInfo
0        2987000        0          86400            68.5         W  13926    NaN  150.0    discover  142.0  credit  315.0   87.0   19.0    NaN           NaN           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  2.0  0.0   1.0  1.0   14.0    NaN  13.0   NaN  NaN NaN NaN NaN NaN  13.0   13.0  NaN  NaN  NaN    0.0    T    T    T   M2    F    T  NaN  NaN  NaN  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   1.0   0.0  0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   0.0   117.0    0.0   0.0    0.0    0.0   0.0   117.0    0.0   0.0   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN           NaN            NaN   NaN   NaN   NaN    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   117.0    0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0   0.0   117.0    0.0   0.0   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN       NaN    NaN    NaN   NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN   NaN   NaN       NaN          NaN                  NaN    NaN        NaN             NaN   NaN   NaN   NaN   NaN        NaN                            NaN
1        2987001        0          86401            29.0         W   2755  404.0  150.0  mastercard  102.0  credit  325.0   87.0    NaN    NaN     gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   0.0  NaN NaN NaN NaN NaN   0.0    NaN  NaN  NaN  NaN    0.0  NaN  NaN  NaN   M0    T    T  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   0.0     0.0    0.0   0.0    0.0    0.0   0.0     0.0    0.0   0.0   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN           NaN            NaN   NaN   NaN   NaN    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0     0.0    0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0   0.0     0.0    0.0   0.0   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN       NaN    NaN    NaN   NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN   NaN   NaN       NaN          NaN                  NaN    NaN        NaN             NaN   NaN   NaN   NaN   NaN        NaN                            NaN
2        2987002        0          86469            59.0         W   4663  490.0  150.0        visa  166.0   debit  330.0   87.0  287.0    NaN   outlook.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   0.0  NaN NaN NaN NaN NaN   0.0  315.0  NaN  NaN  NaN  315.0    T    T    T   M0    F    F    F    F    F  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   0.0     0.0    0.0   0.0    0.0    0.0   0.0     0.0    0.0   0.0   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN           NaN            NaN   NaN   NaN   NaN    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0     0.0    0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0   0.0     0.0    0.0   0.0   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN       NaN    NaN    NaN   NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN   NaN   NaN       NaN          NaN                  NaN    NaN        NaN             NaN   NaN   NaN   NaN   NaN        NaN                            NaN
3        2987003        0          86499            50.0         W  18132  567.0  150.0  mastercard  117.0   debit  476.0   87.0    NaN    NaN     yahoo.com           NaN  2.0  5.0  0.0  0.0  0.0  4.0  0.0  0.0  1.0  0.0  1.0  0.0  25.0  1.0  112.0  112.0   0.0  94.0  0.0 NaN NaN NaN NaN  84.0    NaN  NaN  NaN  NaN  111.0  NaN  NaN  NaN   M0    T    F  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  48.0  28.0  0.0  10.0   4.0   1.0  38.0  24.0   0.0   0.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  50.0  1758.0  925.0   0.0  354.0  135.0  50.0  1404.0  790.0   0.0   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN           NaN            NaN   NaN   NaN   NaN    NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0  28.0   0.0   0.0   0.0   0.0  10.0   0.0   4.0   0.0   0.0   1.0   1.0   1.0   1.0  38.0  24.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  50.0  1758.0  925.0   0.0  354.0   0.0  135.0   0.0   0.0   0.0  50.0  1404.0  790.0   0.0   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN      NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN       NaN    NaN    NaN   NaN       NaN    NaN    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN    NaN   NaN   NaN       NaN          NaN                  NaN    NaN        NaN             NaN   NaN   NaN   NaN   NaN        NaN                            NaN
4        2987004        0          86506            50.0         H   4497  514.0  150.0  mastercard  102.0  credit  420.0   87.0    NaN    NaN     gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   NaN  NaN NaN NaN NaN NaN   NaN    NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  0.0   0.0   0.0  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   0.0     0.0    0.0   0.0    0.0    0.0   0.0     0.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   6.0  18.0  140.0   0.0   0.0   0.0   0.0  1803.0  49.0  64.0   0.0   0.0   0.0   0.0   0.0   0.0  15557.990234  169690.796875   0.0   0.0   0.0  515.0  5155.0  2840.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0   1.0   0.0     0.0    0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0   0.0     0.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0    0.0  70787.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  100.0  NotFound    NaN -480.0   New  NotFound  166.0    NaN  542.0  144.0    NaN    NaN   NaN    NaN    NaN    NaN   NaN   New  NotFound  Android 7.0  samsung browser 6.2   32.0  2220x1080  match_status:2     T     F     T     T     mobile  SAMSUNG SM-G892A Build/NRD90M

In [5]:
print(f"Train shape: {train.shape}")

Train shape: (590540, 434)

In [6]:
fraud_counts = train["isFraud"].value_counts()
fraud_rate = train["isFraud"].mean() * 100

print(fraud_counts)
print(f"\nFraud rate: {fraud_rate:.2f}%")

isFraud
0    569877
1     20663
Name: count, dtype: int64

Fraud rate: 3.50%

In [7]:
y = train['isFraud']
X = train.drop(columns=['isFraud', 'TransactionID'])

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")

X shape: (590540, 432)
y shape: (590540,)

In [8]:
X['email_match'] = (X['P_emaildomain'] == X['R_emaildomain']).astype(np.int8)
print(X['email_match'].value_counts())

email_match
0    488036
1    102504
Name: count, dtype: int64

# 2. Cleaning

In [9]:
missing_rate = X.isnull().mean()
high_missing_columns = missing_rate[missing_rate > 0.5].index.tolist()
missing_flags = X[high_missing_columns].isnull().astype(np.int8)

missing_flags.columns = [f"{col}_missing" for col in high_missing_columns]

X = pd.concat([X.drop(columns=high_missing_columns), missing_flags],axis=1).copy() 

print(f"Columns dropped: {len(high_missing_columns)}")
print(f"Missing flag columns added: {len(high_missing_columns)}")
print(f"Total columns after: {X.shape[1]}")

Columns dropped: 214
Missing flag columns added: 214
Total columns after: 433

In [10]:
num_cols = X.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = X.select_dtypes(include=['object']).columns.tolist()

In [11]:
from sklearn.preprocessing import LabelEncoder

lable_encoder = LabelEncoder()
for col in cat_cols:
    X[col] = X[col].fillna('unknown')
    X[col] = lable_encoder.fit_transform(X[col].astype(str))

print(f"Categorical columns encoded: {len(cat_cols)}")
print(f"Missing values remaining: {X.isnull().sum().sum()}")

Categorical columns encoded: 9
Missing values remaining: 12674972

In [12]:
missing_in_cat = X[cat_cols].isnull().sum().sum()
missing_in_num = X[num_cols].isnull().sum().sum()

print(f"Missing in categorical cols: {missing_in_cat}")
print(f"Missing in numeric cols: {missing_in_num}")

Missing in categorical cols: 0
Missing in numeric cols: 12674972

In [ ]:
cols_after_cleaning = X.shape[1]

with mlflow.start_run(run_name="LR_Cleaning"):
    mlflow.log_params({
        "missing_threshold":          0.5,
        "high_missing_cols_dropped":  len(high_missing_columns),
        "missing_flag_cols_added":    len(high_missing_columns),
        "email_match_feature_added":  True,
        "label_encoding":             True,
        "cat_cols_encoded":           len(cat_cols),
    })
    mlflow.log_metrics({
        "total_columns_after_cleaning": cols_after_cleaning,
        "total_rows":                   X.shape[0],
    })

# 3. Feature Engineering

In [13]:
X['hour'] = (X['TransactionDT'] // 3600) % 24
X['day']  = (X['TransactionDT'] // (3600 * 24)) % 7

X['TransactionAmt_log'] = np.log1p(X['TransactionAmt'])
X['TransactionAmt_cents'] = X['TransactionAmt'] % 1

print(f"Total features: {X.shape[1]}")

Total features: 437

In [14]:
for col in ['card1', 'card2', 'addr1', 'P_emaildomain']:
    print(f"{col}: {X[col].isnull().sum()} missing")

card1: 0 missing
card2: 8933 missing
addr1: 65706 missing
P_emaildomain: 0 missing

In [15]:
X['user_id'] = (
    X['card1'].fillna(-1).astype(str) + '_' +
    X['card2'].fillna(-1).astype(str) + '_' +
    X['addr1'].fillna(-1).astype(str) + '_' +
    X['P_emaildomain'].fillna('unknown').astype(str)
)

In [16]:
X['user_id_count'] = X.groupby('user_id')['user_id'].transform('count')
X['user_id_mean_amt'] = X.groupby('user_id')['TransactionAmt'].transform('mean')
X['user_id_std_amt'] = X.groupby('user_id')['TransactionAmt'].transform('std').fillna(0)

print(f"Total features: {X.shape[1]}")
print(f"\nUser ID stats:")
print(X[['user_id_count', 'user_id_mean_amt', 'user_id_std_amt']].describe().round(2))

Total features: 441

User ID stats:
       user_id_count  user_id_mean_amt  user_id_std_amt
count      590540.00         590540.00        590540.00
mean          213.26            135.03           121.30
std           549.82            148.05           155.40
min             1.00              0.48             0.00
25%             7.00             69.37            33.36
50%            28.00            105.52            80.89
75%           141.00            148.50           161.72
max          4002.00           5191.00          8047.75

In [17]:
X['user_amt_zscore'] = (
    (X['TransactionAmt'] - X['user_id_mean_amt']) / 
    X['user_id_std_amt'].replace(0, 1)
)
X['user_amt_ratio'] = X['TransactionAmt'] / X['user_id_mean_amt']

X['user_amt_zscore'] = X['user_amt_zscore'].clip(-5, 5)
X['user_amt_ratio'] = X['user_amt_ratio'].clip(0, 20)
X['user_id_count_log'] = np.log1p(X['user_id_count'])

X = X.drop(columns=['user_id'])
print(f"Final feature count: {X.shape[1]}")

Final feature count: 443

In [ ]:
with mlflow.start_run(run_name="LR_Feature_Engineering"):
    mlflow.log_params({
        "user_id_fields":  "card1_card2_addr1_P_emaildomain",
        "new_features":    "hour, day, TransactionAmt_log, TransactionAmt_cents, user_id_count, user_id_mean_amt, user_id_std_amt, user_amt_zscore, user_amt_ratio, user_id_count_log",
        "zscore_clip":     "(-5, 5)",
        "ratio_clip":      "(0, 20)",
    })
    mlflow.log_metrics({
        "total_features_after_engineering": X.shape[1],
    })

# 4. Training

In [18]:
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
import mlflow.sklearn

import warnings
from sklearn.exceptions import ConvergenceWarning

warnings.filterwarnings("ignore", category=ConvergenceWarning)

In [19]:
from sklearn.base import BaseEstimator, TransformerMixin
from joblib import Parallel, delayed

class IVSelector(BaseEstimator, TransformerMixin):
    def __init__(self, threshold=0.02, sample_size=50_000, random_state=42, n_jobs=-1):
        self.threshold = threshold
        self.sample_size = sample_size      
        self.random_state = random_state    
        self.n_jobs = n_jobs                
        self.iv_scores = {}
        self.selected_features = None
        self.median = None

    def compute_iv(self, X, y_binary, col):
        series = X[col].copy()
        if series.nunique() > 10:
            series = pd.qcut(series, q=10, duplicates='drop')

        df = pd.DataFrame({"col": series, "target": y_binary})
        total_e  = y_binary.sum()
        total_ne = (1 - y_binary).sum()

        grp = df.groupby("col", observed=True)["target"].agg(["sum", "count"])
        grp.columns = ["e", "cnt"]
        grp["ne"] = grp["cnt"] - grp["e"]

        dist_e  = (grp["e"]  + 0.5) / (total_e  + 0.5)
        dist_ne = (grp["ne"] + 0.5) / (total_ne + 0.5)

        return ((dist_e - dist_ne) * np.log(dist_e / dist_ne)).sum()

    def fit(self, X, y):
        X = pd.DataFrame(X).reset_index(drop=True)
        X.columns = [str(c) for c in X.columns]
        y = pd.Series(y).reset_index(drop=True)

        if self.sample_size and len(X) > self.sample_size:
            idx = y.sample(self.sample_size, random_state=self.random_state).index
            X_sample = X.loc[idx].reset_index(drop=True)
            y_sample = y.loc[idx].reset_index(drop=True)
        else:
            X_sample, y_sample = X, y

        if set(y_sample.unique()).issubset({0, 1}):
            y_binary = y_sample.astype(int)
        else:
            self.median = y_sample.median()
            y_binary = (y_sample > self.median).astype(int)

        results = Parallel(n_jobs=self.n_jobs)(
            delayed(self.compute_iv)(X_sample, y_binary, col)
            for col in X_sample.columns
        )
        self.iv_scores = dict(zip(X_sample.columns, results))

        self.selected_features = [
            col for col, iv in self.iv_scores.items() if iv >= self.threshold
        ]
        return self

    def transform(self, X):
        X = pd.DataFrame(X).reset_index(drop=True)
        X.columns = [str(c) for c in X.columns]
        return X[self.selected_features]

In [20]:
class CorrelationFilter(BaseEstimator, TransformerMixin):
    def __init__(self, threshold=0.85, sample_size=50_000, random_state=42):
        self.threshold = threshold
        self.sample_size = sample_size      
        self.random_state = random_state    
        self.features_to_drop = None
        self.selected_features = None

    def fit(self, X, y=None):
        X = pd.DataFrame(X).reset_index(drop=True)
        X.columns = [str(c) for c in X.columns]

        if self.sample_size and len(X) > self.sample_size:
            X_sample = X.sample(self.sample_size, random_state=self.random_state
                                ).reset_index(drop=True)
        else:
            X_sample = X

        corr_matrix = X_sample.corr().abs()  
        upper = corr_matrix.where(
            np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
        )

        self.features_to_drop = set()
        for col in upper.columns:
            if any(upper[col] > self.threshold):
                for partner in upper.index[upper[col] > self.threshold].tolist():
                    if corr_matrix[col].mean() >= corr_matrix[partner].mean():
                        self.features_to_drop.add(col)
                    else:
                        self.features_to_drop.add(partner)

        self.selected_features = [
            col for col in X.columns if col not in self.features_to_drop
        ]
        return self

    def transform(self, X):
        X = pd.DataFrame(X).reset_index(drop=True)
        X.columns = [str(c) for c in X.columns]
        return X[self.selected_features]

In [21]:
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

In [22]:
base_lr = LogisticRegression(
    solver='saga', class_weight='balanced',
    max_iter=100, random_state=42
)

In [23]:
pipeline_no_selection = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler',  StandardScaler()),
    ('model',   base_lr)
])

pipeline_iv = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('iv',      IVSelector(threshold=0.02)),
    ('scaler',  StandardScaler()),
    ('model',   base_lr)
])

pipeline_iv_corr = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('iv',      IVSelector(threshold=0.02)),
    ('corr',    CorrelationFilter(threshold=0.85)),
    ('scaler',  StandardScaler()),
    ('model',   base_lr)
])

In [24]:
selection_configs = {
    #"LR_Selection_None":    pipeline_no_selection,
    "LR_Selection_IV":      pipeline_iv,
    #"LR_Selection_IV_Corr": pipeline_iv_corr,
}

In [ ]:
selection_results = {}

for run_name, pipeline in selection_configs.items():
    with mlflow.start_run(run_name=run_name):

        pipeline.fit(X_train, y_train)

        if 'iv' in pipeline.named_steps:
            mlflow.log_metric("features_after_iv",
                len(pipeline.named_steps['iv'].selected_features))
        if 'corr' in pipeline.named_steps:
            mlflow.log_metric("features_after_corr",
                len(pipeline.named_steps['corr'].selected_features))

        y_pred = pipeline.predict_proba(X_val)[:, 1]
        auc = roc_auc_score(y_val, y_pred)
        mlflow.log_metric("val_auc", auc)

        selection_results[run_name] = (pipeline, auc)
        print(f"{run_name}: AUC = {auc:.4f}")

In [28]:
import psutil
ram = psutil.virtual_memory()
print(f"Used: {ram.used / 1e9:.1f} GB / Total: {ram.total / 1e9:.1f} GB")

Used: 8.3 GB / Total: 33.7 GB

In [29]:
selection_results = {}
for run_name, pipeline in selection_configs.items():
    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, y_pred)
    selection_results[run_name] = (pipeline, auc)
    print(f"{run_name}: AUC = {auc:.4f}")

best_selection_name, (best_selection_pipeline, best_selection_auc) = max(
    selection_results.items(), key=lambda x: x[1][1]
)
print(f"\nBest selection strategy: {best_selection_name} | AUC: {best_selection_auc:.4f}")

LR_Selection_IV: AUC = 0.8440

Best selection strategy: LR_Selection_IV | AUC: 0.8440

In [30]:
best_selection_name, (best_selection_pipeline, best_selection_auc) = max(
    selection_results.items(), key=lambda x: x[1][1]
)
print(f"\nBest selection strategy: {best_selection_name} | AUC: {best_selection_auc:.4f}")

Best selection strategy: LR_Selection_IV | AUC: 0.8440

In [ ]:
with mlflow.start_run(run_name="LR_Feature_Selection"):
    for run_name, (pipeline, auc) in selection_results.items():
        params = {"strategy": run_name}
        metrics = {"val_auc": auc}
        
        if 'iv' in pipeline.named_steps:
            metrics["features_after_iv"] = len(pipeline.named_steps['iv'].selected_features)
        if 'corr' in pipeline.named_steps:
            metrics["features_after_corr"] = len(pipeline.named_steps['corr'].selected_features)
        
        with mlflow.start_run(run_name=f"summary_{run_name}", nested=True):
            mlflow.log_params(params)
            mlflow.log_metrics(metrics)
    
    mlflow.log_param("best_strategy", best_selection_name)
    mlflow.log_metric("best_val_auc", best_selection_auc)

In [25]:
param_grid_l2 = {'model__penalty': ['l2'], 'model__C': [0.01, 0.1, 1]}
param_grid_l1 = {'model__penalty': ['l1'], 'model__C': [0.01, 0.1, 1]}

In [35]:
def run_and_log(run_name, pipeline, param_grid):
    with mlflow.start_run(run_name=run_name):
        grid = GridSearchCV(
            pipeline, param_grid, cv=skf,
            scoring='roc_auc', n_jobs=2,
            return_train_score=True,
            verbose=3
        )
        grid.fit(X_train, y_train)

        for i, params in enumerate(grid.cv_results_['params']):
            with mlflow.start_run(run_name=f"{run_name}_combo_{i}", nested=True):
                mlflow.log_params(params)
                mlflow.log_metric("cv_auc_mean",       grid.cv_results_['mean_test_score'][i])
                mlflow.log_metric("cv_auc_std",        grid.cv_results_['std_test_score'][i])
                mlflow.log_metric("cv_train_auc_mean", grid.cv_results_['mean_train_score'][i])

        
        best_pipeline = grid.best_estimator_

        train_auc = roc_auc_score(y_train, best_pipeline.predict_proba(X_train)[:, 1])  
        val_auc   = roc_auc_score(y_val,   best_pipeline.predict_proba(X_val)[:, 1])   

        mlflow.log_params(grid.best_params_)
        mlflow.log_metric("cv_auc_mean",  grid.best_score_)
        mlflow.log_metric("cv_auc_std",   grid.cv_results_['std_test_score'][grid.best_index_])
        mlflow.log_metric("train_auc",    train_auc)   
        mlflow.log_metric("val_auc",      val_auc)    
        mlflow.log_metric("overfit_gap",  train_auc - val_auc) 

        print(f"{run_name} | CV: {grid.best_score_:.4f} | Train: {train_auc:.4f} | Val: {val_auc:.4f} | Gap: {train_auc - val_auc:.4f}")

    return grid

In [26]:
import psutil
ram = psutil.virtual_memory()
print(f"Used: {ram.used / 1e9:.1f} GB / Total: {ram.total / 1e9:.1f} GB")

Used: 8.2 GB / Total: 33.7 GB

In [37]:
grid_l2 = run_and_log("LR_CV_L2", best_selection_pipeline, param_grid_l2)
grid_l1 = run_and_log("LR_CV_L1", best_selection_pipeline, param_grid_l1)

Fitting 3 folds for each of 3 candidates, totalling 9 fits

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV 1/3] END model__C=0.01, model__penalty=l2;, score=(train=0.842, test=0.840) total time= 4.1min
[CV 1/3] END model__C=0.1, model__penalty=l2;, score=(train=0.842, test=0.840) total time= 4.4min
[CV 3/3] END model__C=0.1, model__penalty=l2;, score=(train=0.842, test=0.841) total time= 3.9min
[CV 2/3] END model__C=1, model__penalty=l2;, score=(train=0.843, test=0.839) total time= 4.0min
[CV 2/3] END model__C=0.01, model__penalty=l2;, score=(train=0.843, test=0.839) total time= 4.0min
[CV 3/3] END model__C=0.01, model__penalty=l2;, score=(train=0.842, test=0.841) total time= 4.2min
[CV 2/3] END model__C=0.1, model__penalty=l2;, score=(train=0.843, test=0.839) total time= 3.9min
[CV 1/3] END model__C=1, model__penalty=l2;, score=(train=0.842, test=0.840) total time= 3.9min
[CV 3/3] END model__C=1, model__penalty=l2;, score=(train=0.842, test=0.841) total time= 3.9min
🏃 View run LR_CV_L2_combo_0 at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0/runs/f54e4639d8e141789be23884e2eb6d0e
🧪 View experiment at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0
🏃 View run LR_CV_L2_combo_1 at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0/runs/9fcdb179afef418aaffbd060f6d64dfc
🧪 View experiment at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0
🏃 View run LR_CV_L2_combo_2 at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0/runs/51980e3acf0f45659be8797a892cd97e
🧪 View experiment at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0
LR_CV_L2 | CV: 0.8398 | Train: 0.8436 | Val: 0.8440 | Gap: -0.0004
🏃 View run LR_CV_L2 at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0/runs/257de3bd516840ef89e3667c9e06d45b
🧪 View experiment at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0
Fitting 3 folds for each of 3 candidates, totalling 9 fits

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[CV 1/3] END model__C=0.01, model__penalty=l1;, score=(train=0.841, test=0.839) total time= 4.9min
[CV 1/3] END model__C=0.1, model__penalty=l1;, score=(train=0.842, test=0.840) total time= 5.2min
[CV 3/3] END model__C=0.1, model__penalty=l1;, score=(train=0.842, test=0.841) total time= 4.9min
[CV 2/3] END model__C=1, model__penalty=l1;, score=(train=0.843, test=0.839) total time= 5.1min
[CV 2/3] END model__C=0.01, model__penalty=l1;, score=(train=0.842, test=0.838) total time= 4.9min
[CV 3/3] END model__C=0.01, model__penalty=l1;, score=(train=0.841, test=0.840) total time= 4.7min
[CV 2/3] END model__C=0.1, model__penalty=l1;, score=(train=0.843, test=0.839) total time= 5.0min
[CV 1/3] END model__C=1, model__penalty=l1;, score=(train=0.842, test=0.840) total time= 5.1min
[CV 3/3] END model__C=1, model__penalty=l1;, score=(train=0.842, test=0.841) total time= 4.9min
🏃 View run LR_CV_L1_combo_0 at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0/runs/edc663f0858845a6bf8c807bf2591a68
🧪 View experiment at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0
🏃 View run LR_CV_L1_combo_1 at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0/runs/d361837c2d674b7eb2bd692b8687d501
🧪 View experiment at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0
🏃 View run LR_CV_L1_combo_2 at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0/runs/1985a003137a42b2b066c1e6e9370df0
🧪 View experiment at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0
LR_CV_L1 | CV: 0.8398 | Train: 0.8436 | Val: 0.8440 | Gap: -0.0004
🏃 View run LR_CV_L1 at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0/runs/418607deaa59462493613fe336460faf
🧪 View experiment at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0

In [39]:
def evaluate(grid):
    model = grid.best_estimator_
    y_pred = model.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, y_pred)
    return model, auc

In [42]:
model_l2, auc_l2 = evaluate(grid_l2)
model_l1, auc_l1 = evaluate(grid_l1)

print(f"L2 AUC: {auc_l2:.8f}")
print(f"L1 AUC: {auc_l1:.8f}")

L2 AUC: 0.84400874
L1 AUC: 0.84400425

# 5. Evaluation & Model Registry

In [43]:
models = {
    "L2": (model_l2, auc_l2),
    "L1": (model_l1, auc_l1),
}

best_name, (best_model, best_auc) = max(models.items(), key=lambda x: x[1][1])
print(f"\nBest LR Model: {best_name} | AUC: {best_auc:.4f}")

with mlflow.start_run(run_name="LR_Final_Model"):
    mlflow.log_param("best_penalty",            best_name)
    mlflow.log_param("best_selection_strategy", best_selection_name)
    mlflow.log_metric("val_auc",                best_auc)
    mlflow.sklearn.log_model(
        best_model,
        artifact_path="pipeline_model",
        registered_model_name="LogisticRegression_Best"
    )

Best LR Model: L2 | AUC: 0.8440

2026/05/01 21:43:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/01 21:43:09 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Successfully registered model 'LogisticRegression_Best'.
2026/05/01 21:43:29 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: LogisticRegression_Best, version 1
Created version '1' of model 'LogisticRegression_Best'.

🏃 View run LR_Final_Model at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0/runs/19f8229259cc4160a31ba30fcbc344c6
🧪 View experiment at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0

In [28]:
#best_params = grid_l2.best_params_  

#best_lr_params = {k.replace("model__", ""): v for k, v in best_params.items()}
#print(best_lr_params) 

best_lr = LogisticRegression(
    solver='saga',
    class_weight='balanced',
    max_iter=500,
    random_state=42,
    C=1,
    penalty='l2'
)

In [29]:
class MergeIdentityTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, identity_df):
        self.identity_df = identity_df

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X.merge(self.identity_df, on="TransactionID", how="left")

In [30]:
class DropIDTransformer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X.drop(columns=['TransactionID'], errors='ignore').reset_index(drop=True)

In [31]:
class EmailMatchTransformer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()
        X['email_match'] = (X['P_emaildomain'] == X['R_emaildomain']).astype(np.int8)
        return X

In [32]:
class MissingFlagTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, threshold=0.5):
        self.threshold = threshold
        self.high_missing_columns = None

    def fit(self, X, y=None):
        missing_rate = X.isnull().mean()
        self.high_missing_columns = missing_rate[missing_rate > self.threshold].index.tolist()
        return self

    def transform(self, X):
        X = X.copy()
        missing_flags = X[self.high_missing_columns].isnull().astype(np.int8)
        missing_flags.columns = [f"{col}_missing" for col in self.high_missing_columns]
        return pd.concat([X.drop(columns=self.high_missing_columns), missing_flags], axis=1)

In [33]:
class LabelEncodeTransformer(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.encoders = {}
        self.cat_cols = None

    def fit(self, X, y=None):
        self.cat_cols = X.select_dtypes(include=['object']).columns.tolist()
        for col in self.cat_cols:
            le = LabelEncoder()
            le.fit(X[col].fillna('unknown').astype(str))
            self.encoders[col] = le
        return self

    def transform(self, X):
        X = X.copy()
        for col in self.cat_cols:
            X[col] = X[col].fillna('unknown').astype(str)
            known = set(self.encoders[col].classes_)
            X[col] = X[col].apply(lambda v: v if v in known else 'unknown')
            X[col] = self.encoders[col].transform(X[col])
        return X

In [34]:
class FeatureEngineeringTransformer(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.user_stats = None 

    def fit(self, X, y=None):
        X = X.copy()
        X['user_id'] = (
            X['card1'].fillna(-1).astype(str) + '_' +
            X['card2'].fillna(-1).astype(str) + '_' +
            X['addr1'].fillna(-1).astype(str) + '_' +
            X['P_emaildomain'].fillna('unknown').astype(str)
        )
        self.user_stats = (
            X.groupby('user_id')['TransactionAmt']
            .agg(['count', 'mean', 'std'])
            .rename(columns={'count': 'uid_count', 'mean': 'uid_mean', 'std': 'uid_std'})
        )
        return self

    def transform(self, X):
        X = X.copy()

        X['hour'] = (X['TransactionDT'] // 3600) % 24
        X['day']  = (X['TransactionDT'] // (3600 * 24)) % 7

        X['TransactionAmt_log']   = np.log1p(X['TransactionAmt'])
        X['TransactionAmt_cents'] = X['TransactionAmt'] % 1

        X['user_id'] = (
            X['card1'].fillna(-1).astype(str) + '_' +
            X['card2'].fillna(-1).astype(str) + '_' +
            X['addr1'].fillna(-1).astype(str) + '_' +
            X['P_emaildomain'].fillna('unknown').astype(str)
        )

        X = X.join(self.user_stats, on='user_id')
        X = X.rename(columns={
            'uid_count': 'user_id_count',
            'uid_mean':  'user_id_mean_amt',
            'uid_std':   'user_id_std_amt'
        })
        X['user_id_std_amt'] = X['user_id_std_amt'].fillna(0)

        X['user_amt_zscore'] = (
            (X['TransactionAmt'] - X['user_id_mean_amt']) /
            X['user_id_std_amt'].replace(0, 1)
        ).clip(-5, 5)
        X['user_amt_ratio']    = (X['TransactionAmt'] / X['user_id_mean_amt']).clip(0, 20)
        X['user_id_count_log'] = np.log1p(X['user_id_count'])

        X = X.drop(columns=['user_id'])
        return X

In [35]:
full_pipeline = Pipeline([
    ('drop_id',  DropIDTransformer()),
    ('email',    EmailMatchTransformer()),
    ('missing',  MissingFlagTransformer(threshold=0.5)),
    ('encode',   LabelEncodeTransformer()),
    ('features', FeatureEngineeringTransformer()),
    ('imputer',  SimpleImputer(strategy='median')),
    ('iv',       IVSelector(threshold=0.02)),
    ('scaler',   StandardScaler()),
    ('model',    best_lr)
])

In [37]:
X_raw = train_transaction.merge(train_identity, on="TransactionID", how="left")
y = X_raw['isFraud']
X_raw = X_raw.drop(columns=['isFraud'])

X_train_raw, X_val_raw, y_train, y_val = train_test_split(
    X_raw, y, test_size=0.2, random_state=42, stratify=y
)

In [38]:
full_pipeline.fit(X_train_raw, y_train)
val_auc = roc_auc_score(y_val, full_pipeline.predict_proba(X_val_raw)[:, 1])

In [39]:
with mlflow.start_run(run_name="LR_Final_Pipeline"):
    mlflow.log_params({
        "C": 1,
        "penalty": "l2",
        "solver": "saga",
        "iv_threshold": 0.02,
        "missing_threshold": 0.5,
        "imputer_strategy": "median",
        "scaler": "StandardScaler",
    })
    mlflow.log_metric("val_auc", val_auc)
    mlflow.log_metric(
        "n_selected_features",
        len(full_pipeline.named_steps['iv'].selected_features)
    )

    mlflow.sklearn.log_model(
        full_pipeline,
        artifact_path="full_pipeline",
        registered_model_name="LR_FullPipeline"
    )
    print(f"Final pipeline VAL AUC: {val_auc:.4f}")

2026/05/02 11:26:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/02 11:26:40 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Successfully registered model 'LR_FullPipeline'.
2026/05/02 11:26:56 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: LR_FullPipeline, version 1
Created version '1' of model 'LR_FullPipeline'.

Final pipeline VAL AUC: 0.8443
🏃 View run LR_Final_Pipeline at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0/runs/b307734220724b4ab458695136df9167
🧪 View experiment at: https://dagshub.com/aochi23/ml_assn_02.mlflow/#/experiments/0

In [40]:
model = mlflow.pyfunc.load_model("models:/LR_FullPipeline/1")

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

In [49]:
sk_model = model._model_impl.sklearn_model

print(sk_model)
for k, v in sk_model.get_params().items():
    print(k, ":", v)

Pipeline(steps=[('drop_id', DropIDTransformer()),
                ('email', EmailMatchTransformer()),
                ('missing', MissingFlagTransformer()),
                ('encode', LabelEncodeTransformer()),
                ('features', FeatureEngineeringTransformer()),
                ('imputer', SimpleImputer(strategy='median')),
                ('iv', IVSelector()), ('scaler', StandardScaler()),
                ('model',
                 LogisticRegression(C=1, class_weight='balanced', max_iter=500,
                                    random_state=42, solver='saga'))])
memory : None
steps : [('drop_id', DropIDTransformer()), ('email', EmailMatchTransformer()), ('missing', MissingFlagTransformer()), ('encode', LabelEncodeTransformer()), ('features', FeatureEngineeringTransformer()), ('imputer', SimpleImputer(strategy='median')), ('iv', IVSelector()), ('scaler', StandardScaler()), ('model', LogisticRegression(C=1, class_weight='balanced', max_iter=500, random_state=42,
                   solver='saga'))]
transform_input : None
verbose : False
drop_id : DropIDTransformer()
email : EmailMatchTransformer()
missing : MissingFlagTransformer()
encode : LabelEncodeTransformer()
features : FeatureEngineeringTransformer()
imputer : SimpleImputer(strategy='median')
iv : IVSelector()
scaler : StandardScaler()
model : LogisticRegression(C=1, class_weight='balanced', max_iter=500, random_state=42,
                   solver='saga')
missing__threshold : 0.5
imputer__add_indicator : False
imputer__copy : True
imputer__fill_value : None
imputer__keep_empty_features : False
imputer__missing_values : nan
imputer__strategy : median
iv__n_jobs : -1
iv__random_state : 42
iv__sample_size : 50000
iv__threshold : 0.02
scaler__copy : True
scaler__with_mean : True
scaler__with_std : True
model__C : 1
model__class_weight : balanced
model__dual : False
model__fit_intercept : True
model__intercept_scaling : 1
model__l1_ratio : None
model__max_iter : 500
model__multi_class : deprecated
model__n_jobs : None
model__penalty : l2
model__random_state : 42
model__solver : saga
model__tol : 0.0001
model__verbose : 0
model__warm_start : False

In [51]:
clf = sk_model.named_steps[list(sk_model.named_steps.keys())[-1]]
clf.get_params()

{'C': 1,
 'class_weight': 'balanced',
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 500,
 'multi_class': 'deprecated',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': 42,
 'solver': 'saga',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [59]:
feature_names = sk_model.named_steps['scaler'].get_feature_names_out()

coef_df = pd.DataFrame({
    'feature': feature_names,
    'coefficient': clf.coef_[0]
})

coef_df['abs_coef'] = coef_df['coefficient'].abs()
top_features = coef_df.sort_values(by='abs_coef', ascending=False).head(10)

print(top_features[['feature', 'coefficient']])

    feature  coefficient
23       25    -2.667772
20       22     1.658204
16       18    -1.048741
147     203     0.803965
12       13     0.770935
17       19     0.749145
21       23    -0.701449
19       21     0.696067
129     163    -0.684745
70       85    -0.644600

In [2]:
test_transaction = pd.read_csv(path + "test_transaction.csv")
test_identity    = pd.read_csv(path + "test_identity.csv")

In [61]:
print(test_identity.shape)
print(test_identity.columns[:10])

(141907, 41)
Index(['TransactionID', 'id-01', 'id-02', 'id-03', 'id-04', 'id-05', 'id-06',
       'id-07', 'id-08', 'id-09'],
      dtype='object')

In [62]:
test_df = test_transaction.merge(
    test_identity,
    on="TransactionID",
    how="left"
)

test_df.columns = test_df.columns.str.replace('-', '_')

In [63]:
probs = sk_model.predict_proba(test_df)[:, 1]

In [64]:
submission = pd.DataFrame({
    "TransactionID": test_df["TransactionID"],
    "isFraud": probs
})

In [65]:
submission.head(10)

   TransactionID   isFraud
0        3663549  0.085656
1        3663550  0.331695
2        3663551  0.486218
3        3663552  0.203506
4        3663553  0.238353
5        3663554  0.107074
6        3663555  0.489425
7        3663556  0.317735
8        3663557  0.090963
9        3663558  0.545106

In [67]:
submission.to_csv("logistic_regression_submission.csv", index=False)